name: CI

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Get Dependencies Cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies
        run: yarn install

      - name: Check Prettier
        run: yarn prettier

      - name: Check Lint
        run: yarn lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Get Dependencies Cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

  make:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Get Dependencies Cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies
        run: yarn install

      - name: Make
        run: yarn make
